package com.workpal.keypairmanagement.enums;

public enum ErrorCode {
	DUPLICATE_NAME, DEPENDENTS_NOT_EXIST, LIMIT_EXCEEDED, INSUFFICIENT_CAPACITY, VALIDATION_FAILURE, RESOURCE_NOT_FOUND,
	REQUEST_PARAM_EMPTY, SUBNET_OVERLAP, ALREADY_REPORTED, PRODUCT_NOT_PURCHASED, INVALID_PRIVATE_IP,INVALID_CIDR,
	INTERNAL_SERVER_ERROR, DEPENDENT_EXISTS, QUOTA_FAILED, NOT_VALID_KEY, NATTED_VM
}
